### ISSUE TITLE
Constructron getting stuck while doing a job (trying to path over water when a job doesn't include landfill)

### ISSUE THREAD

**Issue by gabfv** [ILLISIS/Constructron-Continued#103]
I keep having constructons getting stuck trying to path over water when doing jobs (see the image below).
![image](https://user-images.githubusercontent.com/24780542/209335517-de5eee86-6098-4c3e-a12e-ed2191ea8c79.png)
![image](https://user-images.githubusercontent.com/24780542/209335703-11093eae-8be6-433f-9cf0-6eee0a955372.png)
![image](https://user-images.githubusercontent.com/24780542/209335727-8f072b46-d982-4108-a478-ffff5bcad376.png)

The surface itself doesn't have any jobs that include landfill, and thus, it never requests for any landfill to do the job, even though it try to path over water.

I tried to look over the code before opening the issue but couldn't find where exactly the problem would be. Could it be that adding a check if it's trying to path over water for position_done? Or would that affect landfill jobs too?

As for the save, the save is roughly 400 MB, do you know somewhere I can upload that?
I'm on Factorio 1.1.74 and my mod list is:
      base
      aai-containers
      aai-industry
      aai-signal-transmission
      Advanced-Electric-Revamped-v16
      AdvancedArtilleryRemotesContinued
      advanced_centrifuge
      AfraidOfTheDark
      alien-biomes
      auto-deploy-combat-robots
      AutoDeconstruct
      AutoTrash
      Battery-Pack
      battery-powered
      BetterBotsWLK
      BigFluidWagon
      bigger-artillery
      blueprint-sandboxes
      BlueprintTools
      bobinserters
      BottleneckLite
      combat-mechanics-overhaul
      Constructron-Continued
      Crafting_Speed_Research
      Deadlock-AAII-bridge
      deadlock-beltboxes-loaders
      Deadlock-SE-bridge
      DeadlockStackingExtended
      DeadlockStackingForKrastorio2
      DeadlockStackingForVanilla
      deadlock_stacked_recipes
      epic_mining_and_crafting_speed_research
      equipment-gantry
      even-distribution
      Exoskeleton Mark II
      factoryplanner
      FactorySearch
      filter-increase
      flib
      FluidMustFlow
      FluidMustFlowSE
      FluidWagonColorMask
      FNEI
      ghost-counter
      grappling-gun
      helmod
      informatron
      Inventory Sensor
      jetpack
      K2-Fusion-Buff
      Krastorio2
      Krastorio2Assets
      Krastorio2ExoskeletonBoost
      Krastorio2RFAC
      Krastorio2_BioLabModules
      Kruise_Kontrol
      Laboratory_Productivity
      lightArtillery
      LogisticTrainNetwork
      LSlib
      LtnManager
      LTN_Combinator_Modernized
      mining-patch-planner
      ModuleInserterEx
      Nanobots
      NuclearFurnace
      OmegaDrill
      OmegaDrillSE
      PipeVisualizer
      qol_research
      railloader
      RailSignalPlannerNeo
      RateCalculator
      Reinforced-Walls
      resourcehighlighter-dark
      robotworld-continued
      robot_attrition
      Robot_Battery_Research
      rocket-log
      rusty-locale
      SchallRemainsPickup
      se-core-miner-output-helper
      SE_xors_tweaks
      shield-projector
      Shortcuts-ick
      show-max-underground-distance
      simhelper
      solar-calc
      space-exploration
      space-exploration-graphics
      space-exploration-graphics-2
      space-exploration-graphics-3
      space-exploration-graphics-4
      space-exploration-graphics-5
      space-exploration-menu-simulations
      space-exploration-pipes-n-belts
      space-exploration-postprocess
      space-exploration-spaceproductivity
      Space_trains
      SpeedControl
      spidertron-extended
      Spidertron-Start
      Squeak Through
      stdlib
      StoneWaterWell
      StoneWaterWellAndSE
      TaskList
      textplates
      TheArcFurnaceImp
      Transport_Drones
      UltimateResearchQueue
      underground-pipe-pack
      VehicleSnap
      WellPlanner
      WideChests
      WideChestsAllTypes
      WireShortcuts
      Wood_Gasification
      XENO-NuclearFurnace-SE

**Comment by ILLISIS** [comment]
Hi

This is caused when you build two ghosts with a body of water in between. The job chunks merge and the construct positions are calculated based on the size of the job chunk. Water is not taken into account at any stage and tbh I don't see how it can be.

It comes down to the player - what / when / how you do it.

You can try /ctron reset all but ultimately the chunks may merge again and cause the same issue so you may need to remove the ghost on the other side of the water.

**Comment by gabfv** [comment]
Hello, thanks for the reply. I've gone with landfilling the lake before doing a /ctron reset all. It worked.

However, I've got another minor question, do you know how big the chunks are? Are those the same chunks you see in Factorio debug view?

**Comment by ILLISIS** [comment]
The chunks I refer to are not the traditional Factorio map chunks and vary in size and shape greatly.

I had code that I recently lost which displayed them and the construct positions, it isn't hard to reproduce and I will update the dev branch with it at some point.
