### ISSUE TITLE
Add Bob-Mod support.

### ISSUE THREAD

**Issue by flameSla** [ILLISIS/Constructron-Continued#128]
**Constructron** does not use fusion construction bots.

**Comment by ILLISIS** [comment]
Hi

I haven't looked into Bob's mod but it sounds like you haven't specified the robot name in the settings because as far as I am aware, all construction robot types are supported.

**Comment by flameSla** [comment]
You are right, I set "bob-construction-robot-5" in the settings.
Everything works.
