### ISSUE TITLE
Support for modded spidertrons (by generating constructron versions)

### ISSUE THREAD

**Issue by KeinNiemand** [ILLISIS/Constructron-Continued#133]
Right now the vanilla spidertron is the only spidertron that has a construction verison, however it would be very usefull to be able to use modded more or less powerfull spidertrons. 
To support this, you could simply go over all spidertrons in data.raw[spider-vehicle], and then duplicate and modify them to make a constructron version of the spidertron including the recepie. This of course hase to be done in date-updates or date-final-fixes so modded spidertrons to make sure modded spidertrons have loaded. 
After that the mod could just look for a certain name prefix used in the generation for actually controlling the spidertrons in the control stage.

**Comment by KeinNiemand** [comment]
Would you still accept this if I make it a pull request? I'm not going to anytime soon but If I might add this myself if I want to use constructron with modded spidertrons sometimes in the future.

**Comment by ILLISIS** [comment]
With the introduction of quality I foresee a fundamental change coming to the assignment of jobs post 2.0 release so I expect that will be along the same lines at the very least.
