### ISSUE TITLE
Constructrons don't wait for robots in inventory when their first jobs are deconstruction (like only trees)

### ISSUE THREAD

**Issue by gabfv** [ILLISIS/Constructron-Continued#135]
Steps to reproduce :

1. Deconstruct an area with only trees (without cliffs). (I think other entities may work as long as it doesn't need to request items for the deconstruction, like cliffs for example).
2. Setup a logistic network that includes roboport and a storage chest with enough construction robots.
3. Setup a constructron service station along with constructrons (along with proper equipments).

I've included a basic save file, but I've had to compress it slightly further so please unzip it once before loading the save (it was slightly above github's upload limit).
[Constructrons-deconstruction-bug_2.zip](https://github.com/ILLISIS/Constructron-Continued/files/10843232/Constructrons-deconstruction-bug_2.zip)

Mods list and map version should be within the included save but I can submit them here if needed.

**Comment by ILLISIS** [comment]
This is sorted for the next update, thanks!
