### ISSUE TITLE
[CRASH] Canceling the placement of a blueprint with Compact circuits connected

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [ILLISIS/Constructron-Continued#146]
A blueprints containing Compact circuits with connected wires was placed for the blueprint input/output point objects are created. When the placement of the blueprint was canceled, Compact circuits itself and its points were marked for dismantling. drones flew up to them, hovered over them and a crash occurred:

```
 189.969 Error MainLoop.cpp:1382: Exception at tick 32896440: Мод Constructron-Continued (1.0.74) вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event Constructron-Continued::on_nth_tick(15)
__Constructron-Continued__/script/entity_processor.lua:285: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	__Constructron-Continued__/script/entity_processor.lua:285: in function 'add_entities_to_chunks'
	__Constructron-Continued__/control.lua:14: in function <__Constructron-Continued__/control.lua:11>
 189.970 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "Мод Constructron-Continued (1.0.74) вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event Constructron-Continued::on_nth_tick(15)
__Constructron-Continued__/script/entity_processor.lua:285: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	__Constructron-Continued__/script/entity_processor.lua:285: in function 'add_entities_to_chunks'
	__Constructron-Continued__/control.lua:14: in function <__Constructron-Continued__/control.lua:11>"
```

**Comment by ILLISIS** [comment]
Hi
Thanks for your report. I am afraid that I will be trying to fix the issue in the dark if I was to look into this now.

Could you please provide a save game and a way to reproduce the issue?

**Comment by Eldrinn-Elantey** [comment]
If I understood the situation correctly, then the problem can be reproduced even in a new game. I plase my blueprint "0eNq9WuuSolqWfpUK/1qW3C8VMRMBggoiKKCIEycyuAnI/S52VMTMPEY/S0fPK1S/0WCalZWnisxKs07nnzTRtb/1rbU2a397w98GZlg5ae7H5eDz3wZFbKSjMhm5uW9frk+DzxD6cdB2H8iXjwPfSuJi8Pm/OkPfjY3wYlK2qTP4PPBLJxp8HMRGdLkqnFGeWIFTjkKjii1vlBr24AIQ206HCX75+EsIw/BHV5NR7liOXzv5EwToyx8fB05c+qXvXBndX7R3cRWZneVn8DuXyAjDjkeUduBpUnRDkvhbcJ8eovuEfrlw+gEE+hObxsgdL6kusTlZ5RRlZ/ITInaPh3VMu1yVeRLemY5n1H6SXwwsP7cqv7yLEtu5Sw53SerkxnU0eB0SO9blurhYg5c/uWM/je9SFxj/8seXPr7w64L+RdTII0qQj7oonXCU+qlznRdJFds9kOADJNpBfhzYfn4NowPrcYD+uchdlmLXTE4joxtTO6M0T2rf7ksuCNw7IfpYY/2se0C+ccX7w8dvDx8EHiCxH8OHehwQNzPF+pmSb2AKPccU63FwyfeDB9N3R07YGee+NUqTsI8ufk3rMxPZzR0n/nEqQ/BlKndeHN/1zKTKLzczBP/RRwZ8bd6gX+QNhN4ww28qMQj/xj30zLwE/3xfVl3r6LrKyI8LJ+9tRfADHnllnCfp3U/tjwAAnAAfejz4CScxAr9Yp74VVD/Zw/dmI7CXHnojPfR96WE30kPelx5+Iz38l/RG0AOh17EbvUiPuJEe9r70yF56Bz/syL3Akvwzyyer1r9z+Ubwa89LOknT6SznrigNK7gr/LNzr1v6snVd+LqcgSQJgS8l6moJ9coZ4MYqEu9aRaivwVd9CuZxYQSBm+rW/WY/4hz8vCjvflKhtZ+XVffNdyl1FaHU4FrhrlgXrQxcLqLU6Op/8TH4z8GXG2YA9IyAg6CbtQHxjHT98wpUmR3vy/BRFEA9aMi1zrcs3Zfc98jSH9ZyEOhby6Hva1memEma5OWzeuK+xn1VzR3DvgsT1y9K3+p8HYywcD5ev76glpcbq+x+KPOq+96oDT80zNB5HHOXVGVa9cyB+51I57VMSiN8pfljQN/MR/ccLjDfPd/Pn7y6T+8rvb9+yCODp0O+seidI+gbFcVF7z7TEOBPEAB/XxJ/2a4eGkJ/v8Je3lD+3K+uXrEbtlLkdc6WhntvFxpdh4jduw7+7sH1LDfiuCo+CNefPqzuPV9p3HVy2HUvXAeWkbvJ6FB1264uhw8VeuQvGlXtF931OYmdH5AHvbHjb5RT71Ub4o166r34kW8UVC/wG8GPnF5LcfQSRxh4o6p6T47g70mrb1TfS1th1/u5NzWvF1GjF1QUDL1RRb1n1eC3Ve3xIOO9y4b++8uGPFkfO+EWlA/UR36nPy7nnz9n48eq9MpWGP19YOATBoAoBvVKORj7KxxcW2svPv4WfJTEsQvjH/BfXfL7E9wXzoT6iBK3E0VeET/5F8yMTwgAwQiM35IB7Jk4EeDNcYKPZxK9wODvV/oXHqC/IpePHl6fS/C5XMLPEUo7QekURZK/kM2OQG3k/reG9l0nPnlqMgAcMS93UlhBgL4+pBq1aooWoTHCYxQqsFJuI9qV3tjTzVqZ8Asy5I6LlDjSPj3PqFXgHXJ2rPDa1gb5BV5ga0lcoUeX1kFYjOsIEmOvTqPjQkejduuFdESagI4cs9UGW8HoeXNkFFWxpvVYiCNzidGhd/KQJYD4M4bYbQW5mpdtezrVc2bBtTNt3+gWueQSsIZAx/eG2kHVp6y296emMinq2N3L447bxCQ9XrfHh7NJBAnM7Pl2HlnarpGFIcyy+nnI+6qhn3xwWfEItkh3zB6P6rnIY8vY0wi7dtXhLjmKPjJUkcLcrNhYNx2TaWB06uxhwcNOFX8ax/WyltvWgrmxv5oEGrY/6iI8ddnSCuYhORbTdsOlFhZZe0Ca8YSMnM/qGBBcmBzLLWyVDIBHR09QzXY6DwNFbayjfSQJZhWXYx6NufVqCGkQsqnZShX5oqBWK1hV4ygDtIDh81mNT8fQJiQOrtBiLR4vhvaq9ULPPNr4eThT9uZ5jDVhOLf1KWCgUoIqmyyXlyTeOEOOiIbavkqVs7dX9yxoRUdcoHcyN2aWXbbPNGYTXQSVmWlMYq3EFSXuhz4VJrQYyIvKOcx9jJ4omJcIThBNNFG21SkQwfukq/603JYhejDnEKe124yC6d1MMRcpOmt1QZAPEIAaHpvsp4aqFzE9SQEJPtTjscyJzYQJYGVissHRlM+L0p1uHXWaz1Vgrsy2FihUk0W1TJfQUhb2VL5OjsEmXKpBmLFh7co24Cv8mtuzsQQecXBYrKahPYkrnxk6WSlGznBaWI3BoCI/lk6bEgnzLXLEt4kETU8wpshT/dwoFXdwIYjHqWHjUkRAUbS6kU5HyHLPARqLlKRmus5ZM/uo+5jhHrFhgHCcAtQe57dtoFaWpuwjED5aZxw6wDWI7BbTsZehsQws1vTp4GhGe97NMBnBzsjBHzpoVqfrbL+LmtiVXKMxNkNktgimEStka6aAOdEvcbLhUsHaHEw7Wi59R8Y37iSUT7RK6wUmrNYZDEHVjImmW74BdiDtQyxvWD5O+aptxoTGKvvaWglUPT9uTrSYNJmBs/Z+clzx4yWotyeJgI8zaTZfiLI7xibdbNly8uZsV027Aa2G513X7qbuZk3tlhN8b6kQrIECEm29kg3i096Ps0Yuxy5iFICUahblSHxeNdnYIsm1e5YKPJqVDE3YQrAvwImPMfSiBVyrUbqOoheBw7LT7jNaoAAeNDQ9cwBZLw9+RuMKRrJ4kwYUkSm8U7CJJCU8TeYFfIqxebM8KgJNcPHEOslTQtam7hSjfYcsqG0i6tq2mU9MrZLPBz5zD1u6kbgjNa+dlcnE8zWXS3J7pCi/SGfTTbi1BGHROvIaWeBUvJEXVDMkgEaHmL1dHk5iUeXuKTZnyM4+yUYmGmppxNqQriLc4rOTPAudRBDQbZ0UVXkO6yWlQQdzRnGzlDvObMZypvA0MlQyijJ+43bTADSi4VJZmfYGK3CdWpM6uNC93XZrh74WjPeKs3U5GvVkai5WG79YSAGn7thdq7q8KOg2YomTkx1seBfI+VJFlB1FtgwCV0KQ2BBUg5QCYudJFkKuuTaX8c4AZ8HQh5dbjaVcR09iUVf31gxjx3FKVEKGL+wdeLZjHEY0FTVp3wOTNcYyoh3CsxOqRQYGxXKrlkzr4kpRSJu1imoG4WXrCCuXmJGXRqVmDn5a5TKqE/uD7YmzUDrDBEFE6ykZpYxcQVx4ohgVq8dHcGwcLdiBtzNI3MSw3E7S1taDE8z52c5TTzbL4IJ1sBp9ym8E41g5XhTO9vZwjINnZ9GcOQSbULqOMo5CY8vZeAfZgHDKwHG+Ps5OEjhZuaLCqAapVlnllljtgtr2kNNjRWF2TbFdigdukXqFIrKSFmW6EfC1tQM5mNMbOGh3M7kEiJU93mzYVPfZvJBEjDcThTlYZsBvAUueCMxJkVtQ5BhK9litFRl1mVUwD9EaPeMKWzgMN5DEglODBewpxhJTVFrL3DGSwXM6pbAYZnP5EID+PMMiux17vLOZCPFiUtfl8pT4iJxYBE5ipSRKYn3WIuXcIlg9IQPWCMQN0WhZYG6zvZLjLRmHc0gIxxS2IQCKo2EhHPKGsKkV38CHIRjHYxufaoWElbUxnwIOx+MZ1YJzlkhMT/Rmx0aeY2KFzSA6wqsJhG5FftKy6G7ZyMy6bWI2I5ZbO2JmKULnkHauEWZnrraHOEM8GXKqvKBP8vIgHTVKdHFyTR1iEUv94iQtt3A2ieW5eWjqanUUTpTgK1XoR7YHZbxcnU4rqoYbGtxyKReU56NkG3WnT6vVntyVnhrodr5GZYIhxnOOs2npuJRPFrlBUEuSYw0au+mMFJE9G2FDKVjMQbZueDyXcjwfjlfoYbiKV1vqPzrxdNn6hZ0OUlLDcnYfJpeDsA9hYtyflj3sGTuzstuyDT5jOIwSKAn3arU3bNGQTzBJXHT3W/chKPjsRgR9VlSibyH69EHJ7Tzh53ZFCPb7ZL7tPl/P5tnU4L/L5oZjA5B8jgXx2yy+b+j68Mnfx39pG4UCv30n/MIB+OKLVj3PYr4dDF3ff3j185gbzoCQZ2/Ey09PT+ktz+ggwyeH8/L1jazeo3QUuu1dMLD/iRp669tV9zhdSPcPZz4/2TJenh6Y9/S//v3rP//1P1//8fWfX/+v+++///W/H+rL47muBsX15RICRHASwnEIIVAQ+vLl/wHM3hmS" and the drones installed Compact circuits, but I didn't need it and I canceled it via Ctrl+Z, he and his connection points were marked for dismantling and the drones flew to perform it, but after they were caught over the points and a failure occurred. You need to use the blueprint because these points are if only if you save Compact circuits with connected wires
