### ISSUE TITLE
Improve How Constructron deal with Water, Prevent loops of trying to do the same Unreachable job over and over 

### ISSUE THREAD

**Issue by KeinNiemand** [ILLISIS/Constructron-Continued#149]
I tried using this mod in seablock and it really don't work like at all, even with ghost landfill paths already laid out the constructron just decide to build/deconstruct something on a randomly generated island, fail to walk there go back to base and repeat that same task endlessly, they never even try to do another task like placing the ghost landfill that's on the way of where they want to build.

There are serveral way this could be improved, first you could make so that instead of retrying a failed job over and over it puts it on the back of the list and does (or at least tries) other tasks first before it retries whatever at failed doing, this should maybe get to (after a few failed attemts) actually build the ghost landfill that's on the way.
Another things you could do is to do is to enable Logistics While moving and maybe add a setting to always keep landfill in the constructrons inventory, that would let it auto place any landfill that's it's way.
One more issue is that it dosn't pathfind if it tries going to an ureachable place so even if it build ghost landfill on the way it can't even get to the edge of my base if it tries going to an unreachable island, it can go to the edge of my base just fine if it goes to a reachable spot and pathfinds there but for an unreachable spot it tries sending it in a straigh line and dosn't work.

Also since this is Seablock I use Sand from the Landfill paining mod instead of regular landfill in case that matters.

**Comment by KeinNiemand** [comment]
I guess there's also the dumb solution to the problem, just add a version of the constructron that dosn't collide with water and can just walk over it, kinda OP but that would fix any problem it has with water.

**Comment by ILLISIS** [comment]
Hi
Due to the limitations of the games pathfinder, all this is easier said than done I am afraid.

You could adjust the collision mask locally if you wish to use it the way you have described. I am currently focused on the job logic and also partly the pathfinder in the next version.

**Comment by KeinNiemand** [comment]
Does it make sense PR for the collision mask changes (as a setting that's disabled by default) or should I just do it locally for myself? Is it to cheaty to actually add it to the mod?
