### ISSUE TITLE
Crash upon it requesting to work on a new patch of wall I had just placed down

### ISSUE THREAD

**Issue by tigartar** [ILLISIS/Constructron-Continued#158]
Wall in question:
![image](https://github.com/ILLISIS/Constructron-Continued/assets/1614729/9f1d7ad5-f402-4877-a095-b7ba9c460494)

Crash:
The mod Constructron-Continued (1.1.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Constructron-Continued::on_nth_tick(90)
__Constructron-Continued__/script/job_processor.lua:929: attempt to index field '?' (a nil value)
stack traceback:
	__Constructron-Continued__/script/job_processor.lua:929: in function 'calculate_required_inventory_slot_count'
	__Constructron-Continued__/script/job_processor.lua:93: in function <__Constructron-Continued__/script/job_processor.lua:89>
	(...tail calls...)
	__Constructron-Continued__/script/job_processor.lua:80: in function 'find_chunks_in_proximity'
	__Constructron-Continued__/script/job_processor.lua:856: in function 'make_jobs'
	__Constructron-Continued__/script/job_processor.lua:375: in function <__Constructron-Continued__/script/job_processor.lua:372>
	
Additional info:
Before this it had been refusing to construct anything that existed for quite a while just idling and deconstructing trees here and there, it build something once or twice.

**Comment by ILLISIS** [comment]
Hi
Could you please post your mod list?

**Comment by tigartar** [comment]
[mod-list.json](https://github.com/ILLISIS/Constructron-Continued/files/13850147/mod-list.json)

Here you go

**Comment by tigartar** [comment]
Here is a save file from seconds before the crash happens

Tried to load it up a few times and the crash keeps happening the moment the construction comes back home and starts to do its work

[](https://drive.google.com/file/d/1a1oVB3FG7DV4l5EN40lISSahnPsvWMA8/view?usp=sharing)

**Comment by tigartar** [comment]
Deconstructing the station while the constructron is on its way back to it still also gives this error

The mod Constructron-Continued (1.1.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Constructron-Continued::on_nth_tick(90)
__Constructron-Continued__/script/constructron.lua:83: attempt to index local 'constructron' (a nil value)
stack traceback:
	__Constructron-Continued__/script/constructron.lua:83: in function 'get_closest_service_station'
	__Constructron-Continued__/script/job_processor.lua:292: in function 'validate_station'
	__Constructron-Continued__/script/job_processor.lua:384: in function <__Constructron-Continued__/script/job_processor.lua:372>

**Comment by ILLISIS** [comment]
closing this issue we discussed in discord - potentially one off issue after update.
