### ISSUE TITLE
__Constructron-Continued__/script/job_processor.lua:441: attempt to index local 'worker' (a nil value)

### ISSUE THREAD

**Issue by flameSla** [ILLISIS/Constructron-Continued#165]
An error occurred on the server "Main-US"

` 900.793 Error MainLoop.cpp:1391: Exception at tick 3296340: Мод Constructron-Continued (1.1.3) вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event Constructron-Continued::on_nth_tick(90)
__Constructron-Continued__/script/job_processor.lua:441: attempt to index local 'worker' (a nil value)
stack traceback:
	__Constructron-Continued__/script/job_processor.lua:441: in function <__Constructron-Continued__/script/job_processor.lua:387>
 900.793 Error ClientMultiplayerManager.cpp:100: MultiplayerManager failed: "Мод Constructron-Continued (1.1.3) вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event Constructron-Continued::on_nth_tick(90)
__Constructron-Continued__/script/job_processor.lua:441: attempt to index local 'worker' (a nil value)
stack traceback:
	__Constructron-Continued__/script/job_processor.lua:441: in function <__Constructron-Continued__/script/job_processor.lua:387>"
 900.793 Info ClientMultiplayerManager.cpp:616: UpdateTick(3296340) changing state from(InGame) to(Failed)
 965.860 Info ClientMultiplayerManager.cpp:212: Quitting multiplayer connection.
 965.860 Info ClientMultiplayerManager.cpp:616: UpdateTick(3296340) changing state from(Failed) to(Disconnected)
 965.867 Info BlueprintShelf.cpp:724: Saving blueprint storage.
 967.636 Info UDPSocket.cpp:233: Closing socket
 967.636 Info UDPSocket.cpp:263: Socket closed
 969.768 Quitting: user-quit.
 970.108 Goodbye`

**Comment by ILLISIS** [comment]
Hey Flamesla
I am fairly sure we rectified this during the Eternity run, let me know if not, I will close this off in the mean time.
