### ISSUE TITLE
Enhance awaiting logic: items gathering, job validation

### ISSUE THREAD

**Issue by RedRafe** [ILLISIS/Constructron-Continued#171]
**Issue:** 
When contructrons can get the required items from the logistic network, but base is not "big/fast enough" to provide the items. Constructrons get stuck for hours awaiting the items to be delivered.

- This results in fewer jobs to be processed in the same time (i.e. instead of fullfilling 8.5 jobs out of 10, they get stuck at the first that is "long" to complete)
- This also results in invalid job queue: some jobs that get queued while the constructron is awaiting for materials may get fulfilled in the meantime by character/bots, & when the contructron is finally released, it picks up some of these old "ghost" jobs, and tries to go there to deconstruct/build even if it's no more necessary.

**Possible solutions:**
- *Max await time:* Would be cool if there was a max time to let the constructrons gather items from the logistic network, and after that, they get dispatched to build with whatever they have. Something like a 5-10 min time cap would already be a big improvement, instead of having the ctrons waiting for long hours
- Add a validation logic between jobs (or improve, if already present): before a ctron picks up a job (especially for deconstruction ones I noticed), re-validate if there are items in that area to build/deconstruct and get the updated number, if any

**Comment by ILLISIS** [comment]
Hey RedRafe

I believe this is at least partially solved with the selection tool in the last update, I think it would be good to get your opinion on this situation now that the tool is in the wild.

cheers
