### ISSUE TITLE
Automatic Spidertrons, Autotron, Constructron confusion, it's missing

### ISSUE THREAD

**Issue by angrypidgeon123** [ILLISIS/Constructron-Continued#173]
Hello,

I've installed Constructron-Continued_1.1.9 mod, and can't find in the research any Spidertron named "Constructron", "Autotron" or anything remotely similar. Nor in my recipe list

Also there's no "Service Station" structure in my research as suggested by the mod:https://mods.factorio.com/mod/Constructron-Continued

To add to the confusion there's another entry but apparently identical mod https://mods.factorio.com/mod/Autotron

True, I use a rather extensive mod list, but so far I got all the other Spiders from mod I installed, this is the only one missing  https://pastebin.com/41DMUY4b

I use Space Exploration which apparently has modified the vanilla Spidertron recipe to require girders and biomass which I can only get from other planets

I got Constructron in my recipe book mod, not my recipes (E menu), and it doesn't say it's locked by anything, before or after researching Spidertron

Factorio 1.1.104

**Comment by ILLISIS** [comment]
Hi
Constructrons are unlocked with the Spidertron and share the same tech. Constructrons is compatible with vanilla + se/k2 at the very least. If a mod modifies the tech you will need to sort that out, I am not sure which mod would cause this.

**Comment by ILLISIS** [comment]
Hi

I sent that pretty late last night.. so let me reiterate.

AutoTRON is a placeholder mod that Constructrons may get renamed to in the future - you can ignore this

Constructrons are unlocked with the same tech as Spidertrons

SpaceExpl and K2 are compatible with Constructron-Continued, it sounds like you have a mod that modifies the Spidertron research.

**Comment by ILLISIS** [comment]
That will work.

This is what spidertron tech should look like. If it does not, then a different mod is interfering with the research.

![image](https://github.com/ILLISIS/Constructron-Continued/assets/92364928/fc2b08ab-1859-419e-8d37-3b2bf3a7b28c)

**Comment by angrypidgeon123** [comment]
Yes I have another mod that sets the spidertron recipe to only cost green science, while the actual spidertron requires girders and biostuff from Space Exploration meaning it's very late game :D

That research is missing entirely in my game, all that's visible is the 3rd icon in my recipes while pressing 'E' after the "fixes". That was the only thing visible in Recipe Book mod also

![Screenshot 2024-03-20 133706](https://github.com/ILLISIS/Constructron-Continued/assets/154713150/519d9cd2-55a2-4fff-9315-62bf592b7116)


I don't know if it will actually work as I can't build a spidertron atm. I can't see that special roboport icon either anywhere

I suggest extending the mod to accomodate the other spidertron mods with reduced efficiency. I'm using a pentatron atm which has no logistics tab however... perhaps the insectitron has it but haven't researched it yet :)

**Comment by angrypidgeon123** [comment]
early-spidertron_1.4.4 wasn't it, research still doesn't appear in there, probably conflicting with the other spider mods which you can see I have a few. I think you should do it like Space Spidertron mod, which appears in the same research 

![Uploading Screenshot 2024-03-20 141839.png…]()
