### ISSUE TITLE
Request for support with Construction-Planner

### ISSUE THREAD

**Issue by ajklotz** [ILLISIS/Constructron-Continued#174]
Hello, would like to see controlled construction planning with the mod like construction planner.
I've made posts about this in each mods portal and the forum. Some discussion occurred in Discord as well. 

https://mods.factorio.com/mod/ConstructionPlannerContinued/discussion/63e7e75cbb9599424d1025fb
 https://mods.factorio.com/mod/Constructron-Continued/discussion/640163c93548b89bdb5c4e71
https://forums.factorio.com/viewtopic.php?f=28&t=105467

**Comment by fgardt** [comment]
The remote interface in #180 should be enough to solve this. Using a custom event could also be an option but I'm not sure if it would be much better than just passing an entity / array of entities to a remote call directly.

**Comment by azaghal** [comment]
Hm... Kind of a late reply from me on this one (I'm the maintainer ofr Construction Planner Continued), but I have just started getting the integration going from the Construction Planner Continued side, and hit a small snag.

Just for context, from construction planner perspective approve means setting the ghost entity force to player's, and unapproving means setting the ghost entity force to approval force (different from player's, but marked as friendly).

Notifying the constructron that new ghost entities have been "built" works great, but if you unapprove the ghosts, the constructron will get stuck in a loop.

If you want me to perhaps open a new ticket for this one, let me know - I could maybe even get some PR cooking if you would find that helpful, btw :)
