### ISSUE TITLE
Constructrons missing/disappearing 

### ISSUE THREAD

**Issue by alej0varas** [ILLISIS/Constructron-Continued#213]
Hi,
Some constructrons "disappeared". Control center shows "Total constructrons 3" and "Available constructrons 17". I only see 3 of them.

Let me know if you need more feedback, I don't know which other information can be useful. I'm raising the issue here because I don't have access to Discord.

Screenshot of control center.
![factorio_constructron_bug_0](https://github.com/user-attachments/assets/c37a1ec3-9840-4f57-88cd-b1e2c993b778)

**Comment by ILLISIS** [comment]
Hi Can you confirm you are on the latest version as I have addressed this issue recently. If you are, can you reproduce the issue and reduce the count further?

**Comment by alej0varas** [comment]
Hi, I was in version 1.1.23. I updated today to 1.1.26. I'll let you know if it happens again.

For those who want to recover their Spidertrons I wrote this code, it allows to add a constructron and put equipment in its grid ;)

```
/c
game.player.surface.create_entity{name = "constructron", position= {10, 10}, force = game.forces.player}
local e = game.player.surface.find_entity('constructron', {10,10})
e.grid.put{name='fusion-reactor-equipment'}
e.grid.put{name='<quipment-name>'}
```

Thanks
