### ISSUE TITLE
Crash in Constructron Control Center UI when expanding a group with down-arrow

### ISSUE THREAD

**Issue by gepandz** [ILLISIS/Constructron-Continued#226]
## Error Description
In the Constructron Control Center UI, I clicked the down-arrow next to one of the sections, and it crashed to main menu with the following message:

> Error while running event Constructron-Continued::on_gui_click (ID 1)
> Unknown sprite "utility/expand_dark"
> stack traceback:
> 	[C]: in function '__newindex'
> 	__Constructron-Continued__/script/ui.lua:379: in function 'event_handler'
> 	__Constructron-Continued__/script/ui.lua:226: in function <__Constructron-Continued__/script/ui.lua:211>

I'd think that it needs to either not have the expansion button, or it looks like it's missing a callback for that event_handler.

## Version Information
Factorio - 2.0.11
Constructron-Continued - 2.0.5

Neat mod! Thanks for the work. :slightly_smiling_face:

**Comment by ILLISIS** [comment]
Thanks for the report!
