### ISSUE TITLE
2.0.15 crash; no user intervention

### ISSUE THREAD

**Issue by hikeonpast** [ILLISIS/Constructron-Continued#241]
The mod Constructron-Continued (2.0.15) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Constructron-Continued::on_nth_tick(90)
Given count value (-1) is too small, allowed values are from 0 to 4294967295
stack traceback:
	[C]: in function 'can_satisfy_request'
	__Constructron-Continued__/script/job.lua:657: in function 'check_roaming_candidate'
	__Constructron-Continued__/script/job.lua:638: in function 'roam_stations'
	__Constructron-Continued__/script/job.lua:911: in function '?'
	__Constructron-Continued__/script/job.lua:860: in function 'execute'
	__Constructron-Continued__/script/job_processor.lua:25: in function 'process_job_queue'
	__Constructron-Continued__/control.lua:21: in function <__Constructron-Continued__/control.lua:20>

**Comment by ILLISIS** [comment]
Do you have a save point that will reproduce this issue?

**Comment by hikeonpast** [comment]
Hit it twice on the same save, but now can't reproduce it from the same file.  I'll post the save if I can successfully reproduce it.
