### ISSUE TITLE
2.0.15 crash on editing waypoints

### ISSUE THREAD

**Issue by hikeonpast** [ILLISIS/Constructron-Continued#242]
The mod Spidertron Patrols (2.5.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event SpidertronPatrols::on_gui_click (ID 1)
__SpidertronPatrols__/scripts/patrol-gui.lua:608: attempt to index field '?' (a nil value)
stack traceback:
	__SpidertronPatrols__/scripts/patrol-gui.lua:608: in function 'handler'
	__SpidertronPatrols__/scripts/patrol-gui.lua:881: in function 'wrapper'
	__SpidertronPatrols__/scripts/gui-lite.lua:156: in function 'handler'
	__SpidertronPatrols__/scripts/gui-lite.lua:186: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>

**Comment by ILLISIS** [comment]
This issue is from Spidertron Patrols, not Spidertron Automation / Constructron-Continued

Please report it here;
https://github.com/tburrows13/SpidertronPatrols

**Comment by hikeonpast** [comment]
If only I could read...  Sorry for the fud.
