### ISSUE TITLE
Configured robot quality does not seem to be honored

### ISSUE THREAD

**Issue by hikeonpast** [ILLISIS/Constructron-Continued#245]
v2.0.15

In the Shift +C+C menu, I have Rare construction bots selected.

![image](https://github.com/user-attachments/assets/1884304a-86d6-49fe-bb16-f60e58e231ec)

If I build a new (Submarine: Maraxsis) and configure with fuel, and add power and roboports to the equipment grid, the top request group is looking for Ordinary quality robots.  (There's also a strange request for zero fuel that gets auto-added that I don't totally understand)

![image](https://github.com/user-attachments/assets/86f26548-c4d8-418a-939f-fbc0b4f59d1e)

**Comment by ILLISIS** [comment]
Existing jobs will not update if you change the robot type

Constructrons don't actually completely support fuel at this time, for it to be requesting a zero amount there is a good likely hood that the fuel was in the ctron's inventory and not the fuel inventory Maraxis adds which is on par with what I know because as far as I have seen the submarines do not support that fuel type.

**Comment by ILLISIS** [comment]
To clarify, you have the right idea to use the second logistic group for fuel as the mod will never touch that, just that you have specified the incorrect fuel type for it to be placed in the right inventory.

![image](https://github.com/user-attachments/assets/bcd289e9-59c7-4a9c-9057-fc686aae2bd8)

**Comment by hikeonpast** [comment]
When you say existing jobs, do you mean construction that hasn't been completed to the satisfaction of the constructron automation?   

I tried to do a clean test, but perhaps I skipped a step.  I first changed the default robot type and then crafted a new submarine.  There are no ghosts that haven't been constructed.  That said, I notice that the first thing that a constructron-enabled submarine does is go and move around where there used to be ghosts, so perhaps the automation doesn't reflect entities that have been built by the engineer?  Just trying to understand so that I can test things more effectively.

As for fuel, the submarine entity does support rocket fuel, but I just confirmed that reducing the quantity of requested fuel to just that which fits in fuel slots causes the zero quantity fuel item to disappear.  Thanks for your help understanding what's going on there.

![image](https://github.com/user-attachments/assets/1ec21bac-cb0c-4210-b75e-572c7b6a94bc)

![image](https://github.com/user-attachments/assets/a1957eb7-b62e-41e7-9f95-f5bdc5ffde29)

**Comment by ILLISIS** [comment]
There is an issue at the moment where entities are processed prematurely which does not give time for robots to invalidate the entities but there is no perfect solution to that either, it is just worse than what could be currently.

You can see and cancel all jobs in the ctron GUI then start fresh from there.
