### ISSUE TITLE
Crash on Constructron placement whilst jobs are in progress

### ISSUE THREAD

**Issue by ILLISIS** [ILLISIS/Constructron-Continued#3]
Error while running event Constructron-continued::on_nth_tick(60)
__Constructron-continued__/control.lua:897: attempt to index field 'logistic_cell' (a nil value)
stack traceback:
	__Constructron-continued__/control.lua:897: in function 'get_job'
	__Constructron-continued__/control.lua:1001: in function <__Constructron-continued__/control.lua:993>

**Comment by ILLISIS** [comment]
@MegaCoolBlood Would you be able to look at this issue as well as it is similar to the on mine whilst jobs are in progress?

**Comment by MegaCoolBlood** [comment]
@ILLISIS not in the next future, I currently have no time besides my studies and work.

**Comment by ILLISIS** [comment]
@MegaCoolBlood all good mate, I managed to get it sorted in v1.0.3. There's still more things to squash if you ever feel like it!
