### ISSUE TITLE
Krastorio 2 Tesla Coil

### ISSUE THREAD

**Issue by raiguard** [ILLISIS/Constructron-Continued#53]
Greetings,

The K2 tesla coil does not work with the Constructrons. This is because when K2 is adding trigger target masks to entities to make them targets for the tesla coils, they check to see if the entity supports the `universal-equipment`. This code runs in `data-updates`. Since you don't run your K2 compatibility code until `data-final-fixes`, the Constructron is skipped and the tesla coil does not work with it.

If you simply rename `data-final-fixes.lua` to `data-updates.lua`, it will fix the issue. Thank you!

Ref: https://github.com/raiguard/krastorio-2/issues/233

**Comment by ILLISIS** [comment]
Hey mate, thanks for that.

https://github.com/ILLISIS/Constructron-Continued/commit/eed20ea3a034d88870c7387a4104db616586dedb

**Comment by ILLISIS** [comment]
subsequent change.. as I am not functioning properly(migraine)

https://github.com/ILLISIS/Constructron-Continued/commit/b03d35fe4d9d3665f12b6163b0495f123124c210
