### ISSUE TITLE
Crash when deconstructing spidertron

### ISSUE THREAD

**Issue by Danielv123** [ILLISIS/Constructron-Continued#6]
![image](https://cdn.discordapp.com/attachments/911973731482599455/929737301276360714/unknown.png)

Caused by deconstructing the spidertron in a world without a robo network while the spidertron was waiting for materials to finish a job.

**Comment by ILLISIS** [comment]
Do you know what colour it was?

**Comment by Danielv123** [comment]
Yellow I think? Not sure. Didn't realize color mattered.

**Comment by ILLISIS** [comment]
Colour doesn't matter, it was just an info gathering method so I had more of an idea of what is happening at the time.
I.e red is deconstructing, blue is Constructing.

**Comment by ILLISIS** [comment]
Fixed in v1.0.7
