### ISSUE TITLE
Space Exploration compatibility planned?

### ISSUE THREAD

**Issue by nicolas-lang** [ILLISIS/Constructron-Continued#8]
In the description it say *"Right now it can't work on any other surface than nauvis. So space exploration etc wouldn't work."*
Is there a plan do change/extend this to allow multi surface compatibility ?

**Comment by ILLISIS** [comment]
Hi
As I am both not the original code creator and also new to LUA scripting I don't believe this is within my ability to implement support for at this time. Should I get to a level where the current issues are fixed, I will seek to add support for other surfaces.

I truly welcome and appreciate all input from other coders!

**Comment by nicolas-lang** [comment]
I looked into the code a bit and it also seems a bit above my available time*skills. Some parts seem rather simple to change , but other places are more complex. Especially the globals table seem like quite a bit to rework.

A good start might be to identify and document the functions where a specific surface is affected and what the challenges might be.
If I have some spare time I might start a new Issue to document that.

**Comment by ILLISIS** [comment]
I'm happy to help if you have any questions as I've started finding my way around the code - mostly on the conditions and actions, you can find me in the official discord of the same name.

**Comment by ILLISIS** [comment]
Hi

I have been working on the code for some time now and I'd like to think I have a pretty good handle on it.

Would you like to schedule some time to talk through this and/or start a new branch to collaborate on?

**Comment by nicolas-lang** [comment]
Hi Illisis,
work has been (and still is)  a bit heavy and I have not yet had the chance to dive into the code as I was initially planning to, but I am still interested in participating in multi-surface compatibility. 
From my perspective the [queue tables (link)](https://github.com/ILLISIS/Constructron-Continued/blob/e3c24c20e450c51f482e59517d1f1465f2f5b1a3/control.lua#L64) would be the main showstopper:
- we need to prevent a constructotron on nauvis trying to service a crafting job on another surface, this will likely affect pathfinding etc. 

At the moment I would expect that this requires a surface specific set of globals-queues

_For a live chat I suppose Discord-Chat (Karoschl#0523) might be the fastest way to connect._

**Comment by ILLISIS** [comment]
Hi
I haven't been successful adding you on Discord unfortunately. Perhaps add me instead Illisis#8421

I think we may not need separate queues per surface as we should be able shortcut that by filtering the chunk surfaces and Constructron surfaces and if they match only then proceed.
[add_ghosts_to_chunks](https://github.com/ILLISIS/Constructron-Continued/blob/18df1eca64512c395e495dfeed44671ab2774e60/control.lua#L345)[function get_job(constructrons)](
https://github.com/ILLISIS/Constructron-Continued/blob/18df1eca64512c395e495dfeed44671ab2774e60/control.lua#L937)

Let me know what you think.

**Comment by ILLISIS** [comment]
I have created a new branch for surface related changes.

https://github.com/ILLISIS/Constructron-Continued/tree/surfaces

**Comment by ILLISIS** [comment]
Surface support released in v1.0.8
