### ISSUE TITLE
[Question] Space Constructron

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [ILLISIS/Constructron-Continued#85]
Hello,

The movement of the Spidertron in space is limited by the presence of platforms or asteroids. There is such a [mod](https://mods.factorio.com/mod/space-spidertron) that adds a space version Spidertron. Is it possible to make a space version of Constructron?

**Comment by ILLISIS** [comment]
Hi

In the mod settings you can enable the thruster Constructron for space zones only.

Join the discord if you have any more questions!
