### ISSUE TITLE
non-recoverable error Constructron-Continued (1.0.40)

### ISSUE THREAD

**Issue by Hidden-Joker** [ILLISIS/Constructron-Continued#93]
Hello. the constructron was working fine with getting the materials until it reached the blueprint i set and started to build them, then i got following error while building:

The mod Constructron-Continued (1.0.38) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Constructron-Continued::on_nth_tick(60)
LuaLogisticNetwork doesn't contain key can_satisfy_request.
stack traceback:
	[C]: in function '__index'
	__Constructron-Continued__/script/constructron.lua:771: in function '?'
	__Constructron-Continued__/script/constructron.lua:370: in function 'do_until_leave'
	__Constructron-Continued__/script/constructron.lua:1358: in function 'do_job'
	__Constructron-Continued__/script/constructron.lua:1371: in function <__Constructron-Continued__/script/constructron.lua:1369>

Thanks for the continuation of the mod btw.

**Comment by ILLISIS** [comment]
Hi

v1.0.40 has been released, I haven't directly fixed that issue but that function has been through a refactor so the issue probably is non-existent in the newer versions

**Comment by Hidden-Joker** [comment]
Thanks for the info. Got the new version now and it works. Issue closed

**Comment by Hidden-Joker** [comment]
Hey, sorry that i have to reopen this but it happened again. same scenario but the other blueprint where the previous error occurred was finished but after some time it happened again when the constructron was at place and was about to start building.
Here is the error code i got:

The mod Constructron-Continued (1.0.40) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Constructron-Continued::on_nth_tick(60)
LuaLogisticNetwork doesn't contain key can_satisfy_request.
stack traceback:
	[C]: in function '__index'
	__Constructron-Continued__/script/constructron.lua:755: in function '?'
	__Constructron-Continued__/script/constructron.lua:356: in function 'do_until_leave'
	__Constructron-Continued__/script/constructron.lua:1318: in function 'do_job'
	__Constructron-Continued__/script/constructron.lua:1331: in function <__Constructron-Continued__/script/constructron.lua:1329>

**Comment by ILLISIS** [comment]
Hi

Could you upload your save with the blueprints in question?

**Comment by Hidden-Joker** [comment]
Hi

after loading the last auosave file before the error it worked. so idk what happened but there is no error anymore.
so i guess i close it now again but when it happens again then i won't reopen it because you are already informed about the bug. Thanks anyways and have a great day!

**Comment by ILLISIS** [comment]
@Hidden-Joker 
Are you using a Factorio version previous to 1.1.62 ?

**Comment by Hidden-Joker** [comment]
@ILLISIS yes i do

**Comment by ILLISIS** [comment]
Yeah that's why, can_satisfy_request was only implemented in 1.1.62
