### ISSUE TITLE
Constructrons trying to build things from the wrong planet

### ISSUE THREAD

**Issue by uGuardian** [ILLISIS/Constructron-Continued#96]
Same as the title says, they try to build something, wander over, stare at the spot for a minute, and then return home.

I think I've finally figured out what might be the cause of this, I think I may have confused the system by placing rocket constructrons and a service dock inside of a spaceship.

**Comment by ILLISIS** [comment]
Hi
I am not familiar with how the service dock work but what should happen is the entity is 'destroyed' and re-created on the other surfaces therefore is re-registered.

Could you try using `/ctron reset all` and, if you can - as there is no way to scroll, check the count's of Constructrons match on each surface.

**Comment by uGuardian** [comment]
I use `/ctron reset all` frequently and they still tend to dispatch orders from the wrong surfaces. Oddly the counts all match up and such, but it just keeps happening. It also seems to happen only between two surfaces at any given time, which is incredibly odd. On further consideration, might it be an issue with my adding the mod mid-game rather than before starting the save?

**Comment by ILLISIS** [comment]
This was resolved in the last update - closing this issue off.
